### ISSUE TITLE
Rimuovere le directory target

### ISSUE THREAD

**Issue by ilgrosso** [CapozXVII/tirasaexercise#1]
I risultati nella compilazione (le directory `target` appunto) *non* vanno fatte gestire a GIT.

**Comment by CapozXVII** [comment]
Ok dovrebbe essere sistemato

**Comment by ilgrosso** [comment]
Bene; ricorda di legare i commit alle issue così da rendere agevole il tracciamento delle modifiche.
Invece di usare il messaggio
> Removed Targets directories

per e2c0afabeb2f29006393b9b05ca2717910e6e84f basta usare

> Removed Targets directories #1
