### ISSUE TITLE
Il logo dell'Enduser è ancora quello standard di Syncope

### ISSUE THREAD

**Issue by ilgrosso** [CapozXVII/tirasaexercise#2]
Mentre quello della Console è stato sostituito sia nella form di login sia all'interno (sebbene in un modo un po' involuto, comunque funzionante), la form di login dell'Enduser mostra ancora il logo di Syncope.

**Comment by CapozXVII** [comment]
Perfetto. Ho sistemato il logo della login dell'Enduser

**Comment by ilgrosso** [comment]
Ottimo :+1:
